sudo: false

language: node_js

os:
  - osx
  - linux

node_js:
  - "6"
  - "8"
  - "9"

before_install:
  - npm install --global npm@latest

git:
  depth: 10

cache:
  yarn: true
  directories:
    - node_modules
