sudo: false

language: node_js

node_js:
  - "6"
  - "7"
  - "8"
  - "9"

before_install:
  - npm install -g npm@latest

git:
  depth: 10

cache:
  yarn: true
  directories:
    - node_modules

os:
  - osx
  - linux