sudo: false

language: node_js

os:
  - osx
  - linux

node_js:
  - "6"
  - "7"
  - "8"
  - "9"

before_install:
  - npm install -g npm@latest

git:
  depth: 10

cache:
  directories:
    - node_modules

script:
    - yarn test
